spring.jpa.hibernate.ddl-auto: validate
spring.jpa.open-in-view: true
spring.h2.console.enabled: true
#management.endpoints.web.base-path: monitoring
management.endpoints.web.exposure.include: '*'
#server:
 # port: 8090

spring.jpa.hibernate.ddl-auto: validate

spring.jpa.open-in-view: true
spring.h2.console.enabled: true
spring.datasource:
    driverClassName: org.h2.Driver
    url: "jdbc:h2:mem:testdb"
    username: sa
    password: ""
spring.jpa:
  database-platform: org.hibernate.dialect.H2Dialect

spring.h2.console.enabled: true

flyway.enabled: true
flyway.locations: classpath:db/migration