CREATE TABLE USER (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	username varchar(255) not null
);

create sequence user_sequence start with 1 increment by 1;

insert into USER(username) values ('Dave');
insert into USER(username) values ('Jarek');
insert into USER(username) values ('Monika');
--
CREATE TABLE ADDRESS (
  street varchar(255) not null,
  zipcode varchar(255) not null,
  city varchar(255) not null
);

insert into ADDRESS(street, zipcode, city) values('Wspolna', '34-300','Pietrzykowice');



